"""message

Revision ID: 102211d47358
Revises: 
Create Date: 2021-12-20 20:33:16.491449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102211d47358'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
