"""Product model quantity and image_url added

Revision ID: 179dbb84c01e
Revises: ac2fc4d52763
Create Date: 2021-12-23 19:38:57.582239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179dbb84c01e'
down_revision = 'ac2fc4d52763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_images_id', table_name='images')
    op.drop_table('images')
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('products', sa.Column('quantity', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'quantity')
    op.drop_column('products', 'image_url')
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('product', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product'], ['products.id'], name='images_product_fkey'),
    sa.PrimaryKeyConstraint('id', name='images_pkey')
    )
    op.create_index('ix_images_id', 'images', ['id'], unique=False)
    # ### end Alembic commands ###
