"""DB Changes

Revision ID: 3ab8ee0f43b0
Revises: 102211d47358
Create Date: 2021-12-20 20:34:04.666986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab8ee0f43b0'
down_revision = '102211d47358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
