"""product and category title shall be unique

Revision ID: ac2fc4d52763
Revises: 3ab8ee0f43b0
Create Date: 2021-12-21 13:56:13.862807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2fc4d52763'
down_revision = '3ab8ee0f43b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['title'])
    op.create_unique_constraint(None, 'products', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
